version: "3.9"

services:

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: campusgrid
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d campusgrid"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  registry:
    image: registry:2
    restart: unless-stopped
    ports: ["5000:5000"]
    volumes:
      - registry_data:/var/lib/registry

  backend:
    build: ./backend
    restart: unless-stopped
    ports: ["8000:8000"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./backend:/app
      - ./results:/app/results
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload




  frontend:
    build: ./frontend
    restart: unless-stopped
    ports: ["3000:80"]
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000

volumes:
  postgres_data:
  registry_data:
